spring:
  application:
    name: yukibot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/yuki_bot?characterEncoding=UTF8&Timezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  redis:
    host: localhost
    port: 6379
    database: 0
    password: ${REDIS_PASSWORD}
    timeout: 3000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-location: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8010

chatgpt:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${CHATGPT_API_KEY}
  model: gpt-3.5-turbo
  max-tokens: 2048
  frequency-penalty: 0
  presence-penalty: 0
  temperature: 0.7
  stream: false

qqbot:
  id: #bot账号
  password: #bot密码
  authority:
    #是否允许从受允许的群内添加bot为好友
    add-from-allowed-groups: true
    #是否允许陌生人添加好友
    add-without-permission: true
    # 添加机器人为好友时需要填写的验证信息
    token-message: yuki
    # 允许的群组
    allowed-groups:
      # mode为配置条件，如根据qq群号分组（id）或不限制（unlimited）
      mode: id
      ids:
        - 0
    # 允许的好友
    allowed-friends:
      # mode为配置条件，如根据qq号分组（id）或qq好友分组（friend-group）分组或不限制（unlimited）
#      mode: unlimited
      mode: id
#      mode: friend-group
      #配置为好友qq号
      ids:
        - 0
      group-name:
        - 我的好友
    #是否允许非好友
    allowed-strangers: false
